services:
  - type: web
    name: baseball-lineup-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: RENDER_SERVICE_NAME
        value: baseball-lineup-app
      # The following variables need to be set in Render dashboard:
      # TEAMSNAP_CLIENT_ID - Your TeamSnap OAuth client ID
      # TEAMSNAP_CLIENT_SECRET - Your TeamSnap OAuth client secret
      # SECRET_KEY - A secure random string for Flask sessions